name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push frontend Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/-coinmaster:latest .
        docker push ghcr.io/${{ github.repository_owner }}/-coinmaster:latest